apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: selenium-node-chrome
    group: selenium-grid
  name: selenium-node-chrome
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      run: selenium-node-chrome
  template:
    metadata:
      labels:
        run: selenium-node-chrome
        group: selenium-grid
    spec:
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome:3.12.0
        env:
        - name: HUB_PORT_4444_TCP_ADDR
          value: selenium-hub-service
        - name: HUB_PORT_4444_TCP_PORT
          value: "4444"
        - name: NODE_MAX_INSTANCES
          value: "6"
        - name: NODE_MAX_SESSION
          value: "3"
        - name: SE_OPTS
          value: "-browserTimeout 60"
        volumeMounts:
          - mountPath: "/dev/shm"
            name: "dshm"
      volumes:
        - name: "dshm"
          emptyDir: 
            medium: "Memory"
      restartPolicy: Always
